{
 "title": "Workload Exporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Sybench Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysbench_threads{cluster_name=\"$cluster\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Sysbench TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sysbench_tps{cluster_name=\"$cluster\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Sybench Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sysbench_latency{cluster_name=\"$cluster\"}",
     "legendFormat": "Latency"
    }
   ]
  }
 ]
}