{
 "title": "Xpand demo",
 "description": "Updated version compatible with Xbench infra",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Nodes in Quorum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mariadb_xpand_cluster_nodes_in_quorum{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total unprotected replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mariadb_xpand_replicas_stats{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Xpand version",
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": {
    "content": "### MariaDB Xpand 6.1 in a single zone\n###  Maxscale"
   },
   "targets": [
    {
     "expr": "mariadb_xpand_cluster_nodes_in_quorum{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "mariadb_xpand_throughput_stats{cluster_name=\"$cluster\"}",
     "legendFormat": "{{stat_name}}"
    }
   ]
  },
  {
   "title": "Late Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mariadb_xpand_late_nodes{cluster_name=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Softfailing Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(mariadb_xpand_softfailing_containers_stats{cluster_name=\"$cluster\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(mariadb_xpand_sessions{cluster_name=\"$cluster\", statement_state=\"executing\", trx_state=\"open\"}[$__interval])",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (Per Node Average)",
   "type": "timeseries",
   "description": "Each stat is the average of all cores per node over the time period.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "last_over_time(mariadb_xpand_cpu_load{cluster_name=\"$cluster\"}[$__interval])",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "DML activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "last_over_time(mariadb_xpand_global_stats{cluster_name=\"$cluster\"}[$__interval])",
     "legendFormat": "{{stat_name}}"
    }
   ]
  },
  {
   "title": "DML response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "last_over_time(mariadb_xpand_response_time_stats{cluster_name=\"$cluster\"}[$__interval])",
     "legendFormat": "{{stat_name}}"
    }
   ]
  },
  {
   "title": "Rebalance activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    { "expr": "mariadb_xpand_rebalancer_stats", "legendFormat": "{{stat_name}}" }
   ]
  },
  {
   "title": "Queue activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 27 },
   "targets": [
    {
     "expr": "mariadb_xpand_queue_stats{cluster_name=\"$cluster\"}",
     "legendFormat": "{{stat_name}}"
    }
   ]
  },
  {
   "title": "Replicas distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(database, nodeid) (last_over_time(mariadb_xpand_replicas_distribution_stats{cluster_name=\"$cluster\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Replay activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 35 },
   "targets": [
    {
     "expr": "mariadb_xpand_queue_replay_stats",
     "legendFormat": "{{stat_name}}"
    }
   ]
  }
 ]
}