{
 "title": "Xpand Stats",
 "description": "Updated version compatible with Xbench infra",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up, cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(mariadb_xpand_qps{cluster_name=\"$cluster\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Transactions per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(mariadb_xpand_tps{cluster_name=\"$cluster\"})",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "CPU Utilization (Cluster Average)",
   "type": "timeseries",
   "description": "Min/Max/Avg of Database (TIL) cores. Each stat is the average of all nodes over the time period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu!=\"0\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu!=\"0\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu!=\"0\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Core0 (Cluster Average)",
   "type": "timeseries",
   "description": "Min/Max/Avg of core 0. Each stat is the average of all nodes over the time period.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu=\"0\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu=\"0\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(mariadb_xpand_cpu_load{cluster_name=\"$cluster\", cpu=\"0\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "CPU Utilization (Per Node Average)",
   "type": "timeseries",
   "description": "Each stat is the average of all cores per node over the time period.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(mariadb_xpand_cpu_load{cluster_name=\"$cluster\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Total disk usage per node",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mariadb_xpand_capacity_disk_total_usage_percent{cluster_name=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mariadb_xpand_io_disk_writes{cluster_name=\"$cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} Writes"
    },
    {
     "expr": "sum(rate(mariadb_xpand_io_disk_reads{cluster_name=\"$cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} Reads"
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(mariadb_xpand_io_disk_written_bytes{cluster_name=\"$cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} Writes"
    },
    {
     "expr": "sum(rate(mariadb_xpand_io_disk_read_bytes{cluster_name=\"$cluster\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{node}} Reads"
    }
   ]
  },
  {
   "title": "Disk IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"write\"})",
     "legendFormat": "{{node}} Write Avg"
    },
    {
     "expr": "min(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"write\"})",
     "legendFormat": "{{node}} Write Min"
    },
    {
     "expr": "max(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"write\"})",
     "legendFormat": "{{node}} Write Max"
    },
    {
     "expr": "avg(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"read\"})",
     "legendFormat": "{{node}} Read Avg"
    },
    {
     "expr": "min(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"read\"})",
     "legendFormat": "{{node}} Read Min"
    },
    {
     "expr": "max(mariadb_xpand_io_disk_latency_seconds{cluster_name=\"$cluster\", name=\"backend-0\", op=\"read\"})",
     "legendFormat": "{{node}} Read Max"
    }
   ]
  },
  {
   "title": "WAL Sync to Disk Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mariadb_xpand_wals_avg_sync_time_seconds{cluster_name=\"$cluster\", name=\"backend-0\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}